### ISSUE TITLE
Issue on gptj quantized repo

### ISSUE THREAD

**Issue by imthebilliejoe** [AlpinDale/pygmalion.cpp#7]
Hi there, sorry if i Write here but i didnt know how to contact you since i open this issue:

https://github.com/IST-DASLab/gptq/issues/17 

about your repo:

https://github.com/AlpinDale/gptq-gptj 

cause i couldnt address this issue in your repo.

can you help me solve the issue or make possible to open issue on your gptq repo?

thank you very much!

**Comment by AlpinDale** [comment]
Hi. I'd recommend opening this issue in the corresponding [repository](https://github.com/AlpinDale/gptq-gptj). Anyhow, the error:
```
Token indices sequence length is longer than the specified maximum sequence length for this model (3403 > 2048). Running this sequence through the model will result in indexing errors.
```
Indicates that your dataset has sequences that are longer than 2048 tokens; you'll need to format your .jsonl (or whatever other format you use) and restrict it to 2048 tokens per sequence (or line, in case of a .jsonl file). You can safely ignore this for the most part.

As for the other error you mentioned, you'll need to setup your CUDA kernel with the `setup_cuda.py` script. There are instructions provided both in my repo and the original one. Closing this issue because it's irrelevant to pygmalion.cpp.

**Comment by imthebilliejoe** [comment]
> Hi. I'd recommend opening this issue in the corresponding [repository](https://github.com/AlpinDale/gptq-gptj).

hi, this is what i wanted to do at first but there is no issue section in your repo (i did some research and apparently you have to specifically enable the issue section when you fork a repo otherwise it will not be present)

![C490D969-0B59-421C-B476-4B863ED38EF9](https://user-images.githubusercontent.com/80759886/231241039-fdb744ce-3a54-4d2d-9a54-9392f1ae4e26.jpeg)

i look forward to continue the conversation in the proper repo when you will enable it!

thank you!

**Comment by AlpinDale** [comment]
I've activated issues for the repo. Thanks for pointing that out.
